name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: dev-ai
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and deploy containers
        run: |
          docker compose -f docker-compose.yml up -d --build
